CREATE DATABASE IF NOT EXISTS lab_mysql;

USE lab_mysql;


DROP TABLE IF EXISTS CARS;

CREATE TABLE CARS (
    VIN VARCHAR(20) PRIMARY KEY,
    MANUFACTURER VARCHAR(20),
    MODEL VARCHAR(10),
    CAR_YEAR INT,
    COLOR VARCHAR(10)
);

DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
    CUSTOMERS_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(50),
    PHONE_NUMBER VARCHAR(20),
    EMAIL VARCHAR(30),
    ADDRESS VARCHAR(50),
    CITY VARCHAR(15),
    STATE VARCHAR(15),
    COUNTRY VARCHAR(15),
    ZIP VARCHAR(10)
);

DROP TABLE IF EXISTS SALESPERSONS;

CREATE TABLE SALESPERSONS (
    STAFF_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(50),
    STORE VARCHAR(30)
);

DROP TABLE IF EXISTS INVOICES;

CREATE TABLE INVOICES (
    INVOICE_NUMBER VARCHAR(20) PRIMARY KEY,
    INVOICE_DATE DATE,
    VIN VARCHAR(20) UNIQUE,
    CUSTOMERS_ID VARCHAR(20),
    STAFF_ID VARCHAR(20),
    FOREIGN KEY (VIN)
        REFERENCES CARS (VIN),
    FOREIGN KEY (CUSTOMERS_ID)
        REFERENCES CUSTOMERS (CUSTOMERS_ID),
    FOREIGN KEY (STAFF_ID)
        REFERENCES SALESPERSONS (STAFF_ID)
);






